import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Watch sample 1",
      image: "/images/a1.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 2",
      image: "/images/a2.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 3",
      image: "/images/a3.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 4",
      image: "/images/a4.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 5",
      image: "/images/a5.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 6",
      image: "/images/a6.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Watch sample 7",
      image: "/images/a7.jpg",
      category: "Watches",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 1",
      image: "/images/s1.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 2",
      image: "/images/s2.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 3",
      image: "/images/s3.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 4",
      image: "/images/s4.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 5",
      image: "/images/s5.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Shoes sample 1",
      image: "/images/s6.jpg",
      category: "Shoes",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 1",
      image: "/images/w1.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 2",
      image: "/images/w2.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 3",
      image: "/images/w3.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 4",
      image: "/images/b1.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 5",
      image: "/images/b2.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 6",
      image: "/images/b3.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 7",
      image: "/images/b4.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
    {
      name: "Bag or Watch sample 8",
      image: "/images/b5.jpg",
      category: "Bags and Wallets",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4,
      numReviews: 10,
      description: " high quality product",
    },
  ],
};

export default data;
